name: 0.0$(Rev:.r)

pr:
  - main

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: isRelease
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
    readonly: true

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
              noCache: true
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--no-restore --configuration Release /p:AssemblyVersion=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber) /p:PackageVersion=$(Build.BuildNumber) /p:Version=$(Build.BuildNumber)'
          - task: DotNetCoreCLI@2
            displayName: Push
            inputs:
              command: 'push'
              packagesToPush: 'src/Expensely.Authentication.Cognito.Jwt/bin/Release/Expensely.Authentication.Cognito.Jwt.$(Build.BuildNumber).nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '4634f7ff-ee1a-49bd-b3de-2f19eb18d3e1'
              allowPackageConflicts: true

  - stage: prerelease
    dependsOn: build
    displayName: Prerelease
    jobs:
      - deployment:
        environment: Prerelease
        pool:
          vmImage: 'vs2017-win2016'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: rvo-vsts-promotepackage-task@3
                  displayName: Promote
                  inputs:
                    feed: '4634f7ff-ee1a-49bd-b3de-2f19eb18d3e1'
                    inputType: 'nameVersion'
                    definition: '3ede5581-4ae6-4cb0-ade3-d3fdfd3883a0'
                    version: '$(Build.BuildNumber)'
                    releaseView: '0b477f7e-e363-4441-97f7-bf3189253564'

  - ${{ if eq(variables.isRelease, 'True') }}:
    - stage: release
      displayName: Release
      dependsOn: prerelease
      jobs:
        - deployment:
          environment: Release
          pool:
            vmImage: 'vs2017-win2016'
          strategy:
            runOnce:
              deploy:
                steps:
                  - task: rvo-vsts-promotepackage-task@3
                    displayName: Promote
                    inputs:
                      feed: '4634f7ff-ee1a-49bd-b3de-2f19eb18d3e1'
                      inputType: 'nameVersion'
                      definition: '3ede5581-4ae6-4cb0-ade3-d3fdfd3883a0'
                      version: '$(Build.BuildNumber)'
                      releaseView: 'f9bccf78-9a6f-4e24-bcd7-b5f77186974c'
